//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEELahore2k18.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    using System.ComponentModel; public partial class Ambassador
    {
        public int Id { get; set; }
        [DisplayName("Name")]
        public string Name { get; set; }
        [DisplayName("Contact No.")]
        public string ContactNo { get; set; }
        [DisplayName("Facebook Id")]
        public string FacebookId { get; set; }
        [DisplayName("Email Id")]
        public string EmailId { get; set; }
        public string CNIC { get; set; }
        public string Institute { get; set; }
        public Nullable<int> StatusId { get; set; }
        [DisplayName("Created At")]        public Nullable<System.DateTime> CreatedAt { get; set; } 
        public string Address { get; set; }
        [DisplayName("City of Residence")]
        public string CityOfResidence { get; set; }
        public string Degree { get; set; }
        [DisplayName("Previous Experiance")]
        public string PreviousExperiance { get; set; }
        [DisplayName("Category")]
        public Nullable<int> AmbassadorCategoryId { get; set; }
        public Nullable<bool> Hostelite { get; set; }
    
        public virtual AmbassadorCategory AmbassadorCategory { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
