//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEELahore2k18.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteersAndAmbassador
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ContactNo { get; set; }
        public string Designation { get; set; }
        public string EmailId { get; set; }
        public string CNIC { get; set; }
        public string Institute { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
