//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEELahore2k18.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Volunteer
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0]{1})\)?([0-9]{3})\)?([0-9]{3})?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]

        public string ContactNo { get; set; }
        public string FacebookId { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "The email address is not valid")]
        public string EmailId { get; set; }
        public string CNIC { get; set; }
        public Nullable<int> InstituteId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Address { get; set; }
        public string CityOfResidence { get; set; }
        public string Degree { get; set; }
        public string PreviousExperiance { get; set; }
        public Nullable<int> VolunteerCategoryId { get; set; }
        public Nullable<bool> Hostelite { get; set; }
        public string Why { get; set; }
        public string ExpectationsFromSEE { get; set; }
    
        public virtual Institute Institute { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
        public virtual VolunteerCategory VolunteerCategory { get; set; }
    }
}
